app/urls.py
from django.urls import path
from . import views

urlpatterns = [
   
    path('', views.doc_file_upload, name='doc_file_upload'),
    path('get_genders/', views.get_genders, name='get_genders'),
    path('get_voices/',views. get_voices, name='get_voices')
   
]

doct_to_audio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #for media files


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models

# Create your models here.

class Language(models.Model):
    name = models.CharField(max_length=100)
    language_code = models.CharField(max_length=20)

    def __str__(self):
        return self.name
class Gender(models.Model):
    language = models.ForeignKey(Language, on_delete=models.CASCADE)  # Corrected the foreign key reference
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Voice(models.Model):
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

app/forms.py
from django import forms

from .models import Language, Gender, Voice

class Doc_Form(forms.Form):
    file_attachment=forms.FileField(label="Upload Document")
    
    language = forms.ModelChoiceField(queryset=Language.objects.all(), label="Select Language")
    
    gender = forms.ModelChoiceField(queryset=Gender.objects.none(), label="Select Gender")
    
    voice = forms.ModelChoiceField(queryset=Voice.objects.none(), label="Select Voice")

    def __init__(self, *args, **kwargs):
        super(Doc_Form, self).__init__(*args, **kwargs)
        # Set the initial queryset for gender and voice fields
        if 'language' in self.data:
            language_id = self.data.get('language')
            self.fields['gender'].queryset = Gender.objects.filter(language_id=language_id)
        if 'gender' in self.data:
            gender_id = self.data.get('gender')
            self.fields['voice'].queryset = Voice.objects.filter(gender_id=gender_id)

app/views.py
from django.shortcuts import render
from .forms import Doc_Form
import os
import boto3
from django.conf import settings
from django.contrib import messages
from .models import Language
import docx2txt
from django.http import JsonResponse
from .models import Gender, Voice


aws_access_key_id = settings.AWS_ACCESS_KEY_ID
aws_secret_access_key = settings.AWS_SECRET_ACCESS_KEY 
region_name = 'ap-southeast-1'




def doc_file_upload(request):
    form = Doc_Form()
    
    if request.method == 'POST':
        form = Doc_Form(request.POST, request.FILES)
        
        if form.is_valid():
            doc_file = request.FILES['file_attachment']
            
            if not doc_file.name.endswith(('.doc', '.docx')):
                messages.error(request, "Please upload a Word document (.doc or .docx).")
            else:
                language_id = form.cleaned_data['language'].id
                gender_id = form.cleaned_data['gender'].id
                voice_id =form.cleaned_data['voice'].id
                audio_files = extract_paragraph_and_generate_audio(doc_file, language_id, gender_id,voice_id)
                
                audio_files_with_url = [{'audio_url': f'{settings.MEDIA_URL}output_audio/{os.path.basename(file)}'} for file in audio_files]
                return render(request, 'doc_file_upload.html', {'audio_files': audio_files_with_url, 'doc_file': doc_file})

        else:
            messages.error(request, "File is not valid.")
    
    return render(request, "doc_file_upload.html", {'form': form})

def extract_paragraph_and_generate_audio(document, language_id, gender_id,voice_id):
    audio_files = []
    output_directory = os.path.join(settings.MEDIA_ROOT, 'output_audio')
    os.makedirs(output_directory, exist_ok=True)
    
    # Extract text from the document
    text = docx2txt.process(document)
    
    # Split text into paragraphs
    paragraphs = [p.strip() for p in text.split('\n\n') if p.strip()]

    # Convert each paragraph into mp3
    for i, paragraph in enumerate(paragraphs):
        print('i',i,'---------------------para:',paragraph)
        output_file = os.path.join(output_directory, f'paragraph_{i+1}.mp3')
        convert_text_to_speech(paragraph, output_file, language_id, gender_id,voice_id)
        audio_files.append(output_file)

    return audio_files



def convert_text_to_speech(text, output_file, language_id, gender_id,voice_id):
    try:
        # Retrieve the gender based on the provided gender_id
        gender = Gender.objects.get(id=gender_id)
        
        # Retrieve the voices associated with the gender
        voices = Voice.objects.filter(gender=gender)
        
        # Select a default voice for the gender (you can customize this logic)
        default_voice = voices.first()  # Or implement your logic to select a default voice
        selected_voice = Voice.objects.get(id=voice_id)
        
        if selected_voice:
            # Initialize Amazon Polly client
            polly_client = boto3.client('polly', region_name=region_name,
                                        aws_access_key_id=aws_access_key_id,
                                        aws_secret_access_key=aws_secret_access_key)
           
            # Synthesize speech
            response = polly_client.synthesize_speech(Text=text, OutputFormat='mp3', 
                                                       VoiceId=selected_voice.name, LanguageCode=selected_voice.gender.language.language_code)
           
            # Write audio stream to file
            with open(output_file, 'wb') as file:
                file.write(response['AudioStream'].read())

            return response['ResponseMetadata']['HTTPHeaders']['x-amzn-requestcharacters'], response['ResponseMetadata']['HTTPStatusCode']
        else:
            # Handle the case where no voice is available for the selected gender
            raise ValueError("No voice available for the selected gender.")
    except (Gender.DoesNotExist, Voice.DoesNotExist, Language.DoesNotExist) as e:
        # Handle the case where one of the objects does not exist
        raise e







def get_genders(request):
    language_id = request.GET.get('language_id')
    if language_id:
        genders = Gender.objects.filter(language_id=language_id).values_list('id', 'name')
        data = {'genders': dict(genders)}
        return JsonResponse(data)
    else:
        return JsonResponse({})

def get_voices(request):
    gender_id = request.GET.get('gender_id')
    language_id = request.GET.get('language_id')
    if gender_id and language_id:
        voices = Voice.objects.filter(gender_id=gender_id).values_list('id', 'name')
        data = {'voices': dict(voices)}
        return JsonResponse(data)
    else:
        return JsonResponse({})
    
def doc_summary(request):
    return render(request,'doc_summary.html')


templates/doc_file_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #8eb7e0; /* Set background color */
            padding: 50px 0; /* Add padding */
        }
        .container {
            background-color: #E6D290; /* Set container background color */
            border-radius: 10px; /* Add border radius */
            box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.1); /* Add box shadow */
            padding: 20px; /* Add padding */
            max-width: 600px; /* Limit container width */
            margin: auto; /* Center container horizontally */
            font-weight: bold;
        }
        .form-label {
            font-weight: bold; /* Make labels bold */
        }
        .btn-dark {
            margin-top: 20px; /* Add margin to submit button */
        }
        .dropdown-toggle::after {
            display: none; /* Hide default dropdown arrow */
        }

        /* Hide the default file input */
        .custom-file input[type="file"] {
            visibility: hidden;
            position: absolute;
        }

        /* Style the custom file input button */
        .custom-file-label::after {
            content: "Browse"; /* Text displayed after the file name */
        }

        /* Hide the "Change" text after file selection */
        .custom-file-label[data-browse]:after {
            content: none; /* Hide the "Change" text */
        }

        /* Optionally, you can style the custom file input container */
        .custom-file {
            position: relative;
            overflow: hidden;
            display: inline-block;
        }

        /* Optionally, you can add some additional styling to the file input button */
        .custom-file-label {
            cursor: pointer;
            background-color: #fff; /* Button background color */
            color: #505050; /* Button text color */
            padding: 0.375rem 0.75rem; /* Button padding */
            border-radius: 0.25rem; /* Button border radius */
            display: inline-block;
            overflow: hidden;
            position: absolute;
            
        }
        .btn-dark {
            background-color: #f4aebe;
            color: #505050;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="text-center">Upload Document</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ form.file_attachment.label_tag }}
                

                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="customFile" name="file_attachment">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
            </div>
            <!-- <div class="form-group">
                <label for="id_language" class="form.language">Select Language:</label>
                <select name="language" id="id_language" class="form-control">
                    <option value="{{form.language}}"></option>
                </select>
            </div> -->
            <div class="form-group">
                <label for="id_language" class="form.language">Select Language:</label>
                <select name="language" id="id_language" class="form-control">
                    <option value="">Select</option>
                    {% for language in form.language.field.queryset %}
                        <option value="{{ language.id }}" {% if form.language.value == language.id %} selected {% endif %}>
                            {{ language.name }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            


            <div class="form-group">
                <label for="id_gender" class="form-label">Select Gender:</label>
                <select name="gender" id="id_gender" class="form-control">
                    <option value="" selected disabled>Select Gender</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_voice" class="form-label">Select Voice:</label>
                <select name="voice" id="id_voice" class="form-control">
                    <option value="" selected disabled>Select Voice</option>
                </select>
            </div>
            <button class="btn btn-dark btn-block" type="submit">Upload File</button>
        </form>
    </div>



        <div class="container">
            <ul>
         
            {% if messages %}
            {% for msg in messages %}
            <li>
                {{msg}}
            </li>
            {% endfor %}{% endif %}
            </ul>
    
    
         
        </div>
    
        <div class="container">
           
            {% if audio_files %}
            <h2>Generated Audio Files:</h2>
            <ul>
                {% for audio_file in audio_files %}
                    <li>
                        
                        <audio controls>
                            <source src="{{ audio_file.audio_url }}" type="audio/mpeg">
                            
                            Your browser does not support the audio element.
                        </audio>
                        
                        <a href="{{ audio_file.audio_url }}" download title="Click here to download"> Download<i class="fas fa-download"></i>  </a>
                        
                       
                    </li>
                    
                {% endfor %}
            </ul>
        {% endif %}
        </div>
    
    
    
    
   

    <!-- Bootstrap Bundle JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.6.2/js/bootstrap.bundle.min.js"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
    $(document).ready(function() {
        // Handle language selection change
        $('#id_language').change(function() {
            var languageId = $(this).val();
            $.ajax({
                url: '/get_genders/',  // URL to fetch gender options based on language
                data: {
                    'language_id': languageId
                },
                dataType: 'json',
                success: function(data) {
                    var genderField = '<option value="" selected disabled>Select Gender</option>';
                    $.each(data.genders, function(key, value) {
                        genderField += '<option value="' + key + '">' + value + '</option>';
                    });
                    $('#id_gender').html(genderField);
                    $('#id_gender').trigger('change');  // Trigger gender change event to populate voice options
                }
            });
        });

        // Handle gender selection change
        $('#id_gender').change(function() {
            var genderId = $(this).val();
            var languageId = $('#id_language').val();
            $.ajax({
                url: '/get_voices/',  // URL to fetch voice options based on gender and language
                data: {
                    'gender_id': genderId,
                    'language_id': languageId
                },
                dataType: 'json',
                success: function(data) {
                    var voiceField = '<option value="" selected disabled>Select Voice</option>';
                    $.each(data.voices, function(key, value) {
                        voiceField += '<option value="' + key + '">' + value + '</option>';
                    });
                    $('#id_voice').html(voiceField);
                }
            });
        });
    });

  
        // Script for updating file input label with selected file name
        $('.custom-file-input').on('change', function() {
            var fileName = $(this).val().split('\\').pop();
            $(this).siblings('.custom-file-label').addClass('selected').html(fileName);
        });
    
    </script>
</body>
</html>